# Generated by Django 4.1.7 on 2023-02-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='Password_confirmation',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='Username',
        ),
    ]
